name: Validate
on: [push]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10 on linux
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install -U -r build_requirements.txt
      - name: Run tox
        run: tox tests
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          
  DockerBuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm64", "x64", "ARM"]
    steps:
      - uses: actions/checkout@v2
      - name: SetupPython 3.10 on linux
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          arch: ${{ matrix.arch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          arch: ${{ matrix.arch }}

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: hanapoulpe/sensor_net:latest
          arch: ${{ matrix.arch }}